config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :posts, only: [ :new, :create ]
  end
  resources :posts, only: [ :show, :edit, :update, :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true
  validates :rating, presence: true, inclusion: 1..10

  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :age, presence: true
  validates :state, inclusion: { in: %w(Minnesota Wisconsin Texas Alabama California Utah), allow_nil: false }

  has_many :posts, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @user = User.find(params[:user_id])
    @post = Post.new
    redirect_to user_path(@user)
  end

  def create
    @post = Post.new(post_params)
    @post.user = User.find(params[:user_id])
    @post.save
    redirect_to user_path(@post.user)
  end

  private

  def post_params
    params.require(:post).permit(:content, :rating)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /users/1
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :age, :bio, :state)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>


<head>

</head>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= simple_form_for [@user, @post] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, collection: 1..10 %>
  <%= f.submit "submit post", class: "btn btn-primary" %>
<% end %>

<%= link_to 'Back', @user %>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :age %>
    <%= f.input :bio %>
    <%= f.input :state, collection: %w(Alabama California Minnesota Texas Utah Wisconsin) %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Bio</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.age %></td>
        <td><%= user.bio %></td>
        <td><%= user.state %></td>
        <td><%= link_to 'Show', user %>|</td>
        <td><%= link_to "Edit", edit_user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path, class: "btn btn-primary"%>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h2>USER:</h2>

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @user.bio %>
</p>

<p>
  <strong>State:</strong>
  <%= @user.state %>
</p>

<%= link_to 'Back', users_path %> |
<%= link_to "Edit", edit_user_path(@user) %>
<hr>


<h2>POSTS:</h2>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Rating </th>
    </tr>
  </thead>

  <tbody>
    <% @user.posts.each do |post| %>
      <tr>
        <td><%= post.content %></td>
        <td><%= post.rating %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<hr>

<h2>New Post</h2>

<%= link_to 'New post', new_user_post_path(@user), class: "btn btn-primary"%>